const commonCard = {
  background: "rgba(255, 255, 255, 0.1)",
  backdropFilter: "blur(20px)",
  WebkitBackdropFilter: "blur(20px)",
  borderRadius: "24px",
  padding: "30px",
  boxShadow: "0 10px 30px rgba(0, 0, 0, 0.1)",
  border: "1px solid rgba(255, 255, 255, 0.2)",
  color: "#FFFFFF"
};

const commonInput = {
  padding: "14px 20px",
  borderRadius: "30px",
  border: "1px solid var(--border)",
  background: "var(--card-bg)",
  color: "var(--text-main)",
  fontSize: "14px",
  outline: "none",
  transition: "all 0.3s ease",
  width: "100%",
  boxSizing: "border-box",
};

const commonButton = {
  background: "linear-gradient(135deg, #8e2de2 0%, #4a00e0 100%)",
  color: "#fff",
  border: "none",
  padding: "14px 25px",
  borderRadius: "30px",
  fontWeight: "700",
  cursor: "pointer",
  transition: "0.3s ease",
  textTransform: "uppercase",
  letterSpacing: "0.5px",
};

export const dashboardStyles = {
  pageWrap: { animation: "fadeIn 0.5s ease" },
  loading: { height: "calc(100vh - 200px)", display: "flex", justifyContent: "center", alignItems: "center", color: "white" },
  kpiGrid: { display: "flex", flexWrap: "nowrap", gap: "25px", marginBottom: "40px", width: "100%", overflowX: "auto", paddingBottom: "10px" },
  kpiCard: { 
    flex: "1 1 0", 
    minWidth: "180px", 
    ...commonCard,
    padding: "24px", 
    display: "flex", 
    alignItems: "center", 
    gap: "15px", 
    transition: "transform 0.3s ease",
  },
  kpiIcon: { fontSize: "24px", background: "rgba(142, 45, 226, 0.1)", color: "#8e2de2", width: 55, height: 55, borderRadius: "15px", display: "flex", alignItems: "center", justifyContent: "center" },
  kpiInfo: { display: "flex", flexDirection: "column" },
  kpiLabel: { fontSize: "13px", color: "rgba(255,255,255,0.7)", fontWeight: "600", marginBottom: "5px", textTransform: "uppercase", letterSpacing: "0.5px" },
  kpiValue: { fontSize: "24px", fontWeight: "800", margin: 0, color: "#FFFFFF" },
  
  topPerformerCard: { 
    background: "rgba(255, 255, 255, 0.15)", 
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    borderRadius: "24px", 
    padding: "35px", 
    marginBottom: "35px", 
    color: "white", 
    display: "flex", 
    alignItems: "center", 
    gap: "30px", 
    border: "1px solid rgba(255, 255, 255, 0.2)",
    boxShadow: "0 15px 35px rgba(0, 0, 0, 0.2)"
  },
  topPerformerIcon: { fontSize: "55px", filter: "drop-shadow(0 4px 6px rgba(0,0,0,0.1))" },
  topPerformerInfo: { flex: 1 },
  topPerformerTitle: { fontSize: "11px", textTransform: "uppercase", fontWeight: "800", opacity: 0.9, marginBottom: "8px", letterSpacing: "1.5px" },
  topPerformerName: { fontSize: "32px", fontWeight: "800", margin: 0, letterSpacing: "-0.5px" },
  topPerformerMeta: { display: "flex", alignItems: "center", gap: "20px", marginTop: "15px", fontSize: "15px", fontWeight: "600" },
  topDivider: { opacity: 0.4 },

  dashboardContent: { display: "flex", flexDirection: "column", gap: "28px" },
  chartsRow: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(350px, 1fr))", gap: "28px" },
  chartCard: { ...commonCard, minHeight: 350, display: "flex", flexDirection: "column", position: "relative" },
  sectionTitle: { fontSize: "17px", fontWeight: "700", marginBottom: "30px", color: "#FFFFFF", display: "flex", alignItems: "center", gap: "10px" },
  
  barContainer: { display: "flex", flexDirection: "column", gap: "20px", flex: 1, justifyContent: "center" },
  barItem: { display: "grid", gridTemplateColumns: "90px 1fr 45px", alignItems: "center", gap: "15px" },
  barLabel: { fontSize: "12px", color: "rgba(255,255,255,0.7)", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.5px" },
  barTrack: { height: 12, background: "rgba(255,255,255,0.05)", borderRadius: "6px", overflow: "hidden" },
  barFill: { height: "100%", borderRadius: "6px", transition: "width 1s ease-in-out" },
  barValue: { fontSize: "13px", fontWeight: "800", textAlign: "right", color: "#FFFFFF" },

  pieContainer: { display: "flex", alignItems: "center", gap: "35px", justifyContent: "center", flexWrap: "wrap", flex: 1 },
  donutWrapper: { position: "relative", width: 200, height: 200, flexShrink: 0 },
  svgPie: { transform: "rotate(-90deg)", borderRadius: "50%", display: "block" },
  donutCenter: { position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)", display: "flex", flexDirection: "column", alignItems: "center", pointerEvents: "none" },
  donutTotal: { fontSize: "36px", fontWeight: "800", color: "#FFFFFF", lineHeight: 1 },
  donutLabel: { fontSize: "12px", color: "rgba(255,255,255,0.7)", textTransform: "uppercase", fontWeight: "700", marginTop: "5px", letterSpacing: "1px" },
  
  chartLegend: { display: "flex", flexDirection: "column", gap: "14px" },
  legendItem: { display: "flex", alignItems: "center", gap: "12px" },
  legendDot: { width: 10, height: 10, borderRadius: "3px" },
  legendText: { fontSize: "13px", color: "rgba(255,255,255,0.7)", fontWeight: "600" },

  emptyWrap: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center" },
  emptyText: { color: "#64748b", fontSize: "14px", fontWeight: "500" },

  tableCard: { ...commonCard, overflowX: "auto" },
  table: { width: "100%", borderCollapse: "separate", borderSpacing: "0 8px" },
  th: { textAlign: "left", padding: "12px 16px", fontSize: "12px", color: "rgba(255,255,255,0.6)", textTransform: "uppercase", borderBottom: "1px solid rgba(255,255,255,0.1)", fontWeight: "800", letterSpacing: "1px" },
  td: { padding: "18px 16px", fontSize: "14px", color: "#FFFFFF", borderBottom: "1px solid rgba(255,255,255,0.1)" },
  tr: { transition: "0.2s", borderRadius: "12px" },
  tableRateBox: { display: "flex", alignItems: "center", gap: "12px", fontWeight: "800", color: "#FFFFFF" },
  miniBarTrack: { width: 70, height: 8, background: "rgba(255,255,255,0.1)", borderRadius: "4px", overflow: "hidden" },
  miniBarFill: { height: "100%", borderRadius: "4px" },
  bestBadge: { background: "rgba(142, 45, 226, 0.1)", color: "#8e2de2", fontSize: "11px", padding: "4px 10px", borderRadius: "8px", fontWeight: "800", whiteSpace: "nowrap", border: "1px solid rgba(142, 45, 226, 0.2)" }
};

export const taskStyles = {
  pageWrap: { animation: "fadeIn 0.5s ease" },
  loading: { height: "calc(100vh - 200px)", display: "flex", justifyContent: "center", alignItems: "center", color: "white" },
  createCard: { ...commonCard, marginBottom: "35px" },
  subTitle: { fontSize: "18px", fontWeight: "700", marginBottom: "25px", color: "#FFFFFF" },
  formGrid: { display: "flex", flexDirection: "column", gap: "20px" },
  formRow: { display: "grid", gridTemplateColumns: "2fr 1.2fr 1.2fr 1fr", gap: "15px", alignItems: "center" },
  formBottomRow: { display: "grid", gridTemplateColumns: "1fr auto", gap: "15px", alignItems: "center" },
  input: commonInput,
  select: { ...commonInput, cursor: "pointer" },
  addBtn: { ...commonButton, height: "42px", display: "flex", alignItems: "center", gap: "8px", padding: "0 20px", fontSize: "12px", borderRadius: "12px" },
  filterRow: { 
    display: "flex", 
    justifyContent: "space-between", 
    alignItems: "center", 
    marginBottom: "30px", 
    padding: "10px 0",
    borderBottom: "1px solid var(--border)" 
  },
  filtersLeft: { display: "flex", alignItems: "center", gap: "20px" },
  filtersRight: { display: "flex", alignItems: "center", gap: "12px" },
  filterSelect: { 
    background: "var(--card-bg)", 
    border: "1px solid var(--border)", 
    color: "var(--text-main)", 
    padding: "8px 16px", 
    borderRadius: "10px", 
    fontSize: "13px", 
    fontWeight: "800",
    outline: "none",
    cursor: "pointer",
    boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
    appearance: "none",
    minWidth: "160px",
    transition: "border-color 0.2s"
  },
  countText: { fontSize: "14px", color: "white", fontWeight: "700", opacity: 0.9, display: "flex", alignItems: "center", gap: "8px" },
  taskGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: "28px" },
  taskCard: { 
    background: "rgba(255, 255, 255, 0.1)", 
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    borderRadius: "24px", 
    padding: "25px", 
    display: "flex", 
    flexDirection: "column", 
    gap: "18px", 
    border: "1px solid rgba(255, 255, 255, 0.2)",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.1)",
    transition: "transform 0.3s cubic-bezier(0.4, 0, 0.2, 1), box-shadow 0.3s ease",
    position: "relative",
    cursor: "pointer"
  },
  cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "12px" },
  taskTitle: { fontSize: "20px", fontWeight: "900", margin: 0, flex: 1, color: "#fff", letterSpacing: "-1px" },
  priorityTag: { fontSize: "10px", fontWeight: "900", textTransform: "uppercase", padding: "5px 12px", borderRadius: "10px", color: "#fff", letterSpacing: "1px" },
  userText: { fontSize: "13px", color: "rgba(255,255,255,0.7)", fontWeight: "600", margin: 0 },
  descText: { 
    fontSize: "13.5px", 
    color: "#fff", 
    margin: 0, 
    lineHeight: "1.6", 
    fontWeight: "500",
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    marginTop: "5px"
  },
  dateText: { fontSize: "12px", fontWeight: "700", margin: 0, color: "rgba(255,255,255,0.7)" },
  textarea: { ...commonInput, borderRadius: "20px", resize: "vertical", minHeight: "48px" },
  actions: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "15px", paddingTop: "15px", borderTop: "1px solid rgba(0,0,0,0.05)" },
  statusBtn: (status) => ({
    background: status === "completed" ? "rgba(16, 185, 129, 0.1)" : status === "in-progress" ? "rgba(142, 45, 226, 0.1)" : "rgba(245, 158, 11, 0.1)",
    color: status === "completed" ? "#10b981" : status === "in-progress" ? "#8e2de2" : "#f59e0b",
    border: "none", padding: "10px 18px", borderRadius: "20px", fontSize: "13px", fontWeight: "700", cursor: "pointer", transition: "0.2s"
  }),
  adminActions: { display: "flex", gap: "12px" },
  iconBtn: { background: "rgba(0,0,0,0.03)", border: "none", cursor: "pointer", fontSize: "16px", padding: "8px", borderRadius: "10px", transition: "0.2s" },
  editForm: { display: "flex", flexDirection: "column", gap: "12px" },
  editActions: { display: "flex", gap: "12px", marginTop: "10px" },
  saveBtn: { background: "#10b981", color: "#fff", border: "none", padding: "10px 20px", borderRadius: "20px", cursor: "pointer", fontWeight: "700" },
  cancelBtn: { background: "#f0f2f5", color: "#64748b", border: "none", padding: "10px 20px", borderRadius: "20px", cursor: "pointer", fontWeight: "700" },
  emptyState: { textAlign: "center", padding: "60px", color: "#64748b", background: "rgba(255, 255, 255, 0.8)", borderRadius: "24px", border: "2px dashed rgba(255, 255, 255, 0.3)", fontWeight: "600" }
};

export const settingsStyles = {
  pageWrap: { animation: "fadeIn 0.5s ease" },
  contentGrid: { display: "flex", flexDirection: "column", gap: 30, alignItems: "stretch", width: "100%" },
  card: commonCard,
  cardTitle: { fontSize: 20, fontWeight: 800, marginBottom: 30, color: "#FFFFFF", display: "flex", alignItems: "center", gap: "10px" },
  avatarSection: { display: "flex", alignItems: "center", gap: 30, marginBottom: 40 },
  avatar: { width: 100, height: 100, borderRadius: "50%", objectFit: "cover", border: "4px solid rgba(142, 45, 226, 0.1)", boxShadow: "0 4px 10px rgba(0,0,0,0.1)" },
  uploadBox: { display: "flex", flexDirection: "column", gap: 8 },
  uploadBtn: { ...commonButton, padding: "10px 20px", fontSize: "13px" },
  mutedText: { fontSize: 13, color: "rgba(255,255,255,0.6)", fontWeight: "500" },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 25, marginBottom: 30 },
  field: { display: "flex", flexDirection: "column", gap: 10 },
  label: { fontSize: 13, fontWeight: "700", color: "rgba(255,255,255,0.7)", textTransform: "uppercase", letterSpacing: "0.5px" },
  input: { ...commonInput, background: "rgba(255,255,255,0.05)", color: "#FFFFFF" },
  passwordWrapper: { position: "relative" },
  eyeBtn: { position: "absolute", right: "15px", top: "50%", transform: "translateY(-50%)", border: "none", background: "transparent", cursor: "pointer", fontSize: 18, color: "#64748b" },
  primaryBtn: { ...commonButton, width: "fit-content", minWidth: "200px", margin: "0 auto", display: "block" },
  dangerBtn: { background: "rgba(239, 68, 68, 0.05)", color: "#ef4444", border: "1px solid rgba(239, 68, 68, 0.2)", padding: "14px 25px", borderRadius: "30px", fontWeight: "700", cursor: "pointer", margin: "20px auto 0", display: "block", width: "fit-content", minWidth: "200px", transition: "0.2s" },
  divider: { margin: "40px 0", border: "none", borderTop: "1px solid rgba(255, 255, 255, 0.1)" }
};
